name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: wasm32-unknown-unknown
      - run: cargo build --verbose
      - run: cargo build --verbose --target wasm32-unknown-unknown
      - run: cargo build --verbose --examples
      - run: cargo build --target=wasm32-unknown-unknown --example demo
      - run: cargo test
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check
